#!/bin/bash
check(){
  if [ $? == 0 ];then
    echo "SUCCESS."
  else
    echo "ERROR."
    exit 1
  fi
}

create_key(){
  if ! [ -f ${user_key_file} ];then
    echo "INFO: 生成本地密钥"
    mkdir -p ${user_home}/.ssh
    ssh-keygen -t dsa -P '' -f ${user_key_file} &> /dev/null
    check
    echo ""
    chown -R ${username}.${username} $user_home
    check
  fi
}

add_user(){
  echo "INFO: 创建远端用户，创建远端.ssh目录"
  if ssh -i ${user_key_file} -p25535 -o StrictHostKeyChecking=no ${username}@${IP} ":" &> /dev/null;then
    echo "远端用户已存在"
    exit 1
  else
    ansible $IP -m shell -a "useradd ${username} && mkdir -p ${user_home}/.ssh" &>/dev/null
    echo "INFO: 创建远端用户"
    check
  fi
}

send_key(){
  echo "INFO: 发送公钥到远程主机" 
  scp -P25535  ${user_key_file}.pub ${IP}:${user_home}/.ssh/authorized_keys &>/dev/null
  check
  echo "INFO: 修改权限"
  ansible $IP -m shell -a "chmod 600 ${user_home}/.ssh/authorized_keys && chown -R ${username}.${username} ${user_home}" &>/dev/null
  check
}
